# Generated by Django 5.2.8 on 2025-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimClient',
            fields=[
                ('client_key', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dim_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_key', models.DateField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('is_workday', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimEmployee',
            fields=[
                ('employee_key', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('available_hours_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'dim_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProject',
            fields=[
                ('project_key', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimResource',
            fields=[
                ('resource_key', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimStatus',
            fields=[
                ('status_key', models.AutoField(primary_key=True, serialize=False)),
                ('status_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dim_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTask',
            fields=[
                ('task_key', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'dim_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactBudget',
            fields=[
                ('pk', models.CompositePrimaryKey('date_key', 'project_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'fact_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactDefectSummary',
            fields=[
                ('pk', models.CompositePrimaryKey('date_key', 'project_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('defect_count_new', models.IntegerField(blank=True, null=True)),
                ('defect_count_resolved', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_defect_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProgressSnapshot',
            fields=[
                ('pk', models.CompositePrimaryKey('date_key', 'task_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('percent_complete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_progress_snapshot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactResource',
            fields=[
                ('pk', models.CompositePrimaryKey('resource_key', 'project_key', 'date_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('resource_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'fact_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactRisk',
            fields=[
                ('pk', models.CompositePrimaryKey('risk_id', 'date_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('risk_id', models.IntegerField()),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('impact_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactTimelog',
            fields=[
                ('pk', models.CompositePrimaryKey('date_key', 'task_key', 'employee_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'fact_timelog',
                'managed': False,
            },
        ),
    ]
